expected_output = {
    "autoconfig_status": "Enable",
    "uplink_allow_list_enforce": {
        "ipv4": False,
        "ipv6": False,
    },
    "ipv4_uplink": {
        "interface": "Vlan1",
        "gw_arp_pass_count": 5,
    },
    "ipv4_preferred_uplink": {
        "interface": "Same as Selected Uplink",
    },
    "ipv6_uplink": {
        "interface": "None",
        "gw_arp_pass_count": 0,
    },
    "ipv6_preferred_uplink": {
        "interface": "Vlan1",
        "gw_arp_pass_count": 0,
    },
    "interfaces": {
        "ipv4": {
            "Vlan1": {
                "score": 8,
                "state": "SELECTED",
                "ip_address": "192.0.2.10",
                "subnet_mask": "255.255.0.0",
                "gateway": "192.0.2.1",
                "gw_probe": "Success",
                "gw_probe_fail": 0,
                "allowed": 1,
            },
            "Vlan110": {
                "score": 4,
                "state": "SCOREDONE",
                "ip_address": "198.51.100.110",
                "subnet_mask": "255.255.0.0",
                "gateway": "198.51.100.1",
                "gw_probe": "Success",
                "gw_probe_fail": 0,
                "allowed": 1,
            },
            "Vlan120": {
                "score": 4,
                "state": "SCOREDONE",
                "ip_address": "203.0.113.120",
                "subnet_mask": "255.255.0.0",
                "gateway": "203.0.113.1",
                "gw_probe": "Success",
                "gw_probe_fail": 0,
                "allowed": 1,
            },
            "Vlan130": {
                "score": 4,
                "state": "SCOREDONE",
                "ip_address": "192.0.2.130",
                "subnet_mask": "255.255.0.0",
                "gateway": "192.0.2.1",
                "gw_probe": "Success",
                "gw_probe_fail": 0,
                "allowed": 1,
            },
            "GigabitEthernet0/0": {
                "score": 5,
                "state": "GWARPTEST",
                "ip_address": "198.51.100.200",
                "subnet_mask": "255.255.255.240",
                "gateway": "0.0.0.0",
                "gw_probe": "Fail",
                "gw_probe_fail": 2,
                "allowed": 1,
            },
        },
        "ipv6": {
            "Vlan110": {
                "score": 4,
                "state": "SCOREDONE",
                "ipv6_address": "2001:db8:110::1",
                "prefix": "64",
                "gateway": "fe80:110::1",
                "gw_probe": "Success",
                "gw_probe_fail": 0,
                "allowed": 1,
            },
            "Vlan120": {
                "score": 4,
                "state": "SCOREDONE",
                "ipv6_address": "2001:db8:120::1",
                "prefix": "64",
                "gateway": "fe80:120::1",
                "gw_probe": "Success",
                "gw_probe_fail": 0,
                "allowed": 1,
            },
            "Vlan130": {
                "score": 4,
                "state": "SCOREDONE",
                "ipv6_address": "2001:db8:130::1",
                "prefix": "64",
                "gateway": "fe80:130::1",
                "gw_probe": "Success",
                "gw_probe_fail": 0,
                "allowed": 1,
            },
            "GigabitEthernet0/0": {
                "score": 0,
                "state": "GWARPTEST",
                "ipv6_address": "2001:db8:8080::1",
                "prefix": "64",
                "gateway": "UNKNOWN",
                "gw_probe": "Fail",
                "gw_probe_fail": 1,
                "allowed": 1,
            },
        },
    },
}
