expected_output = {
    "TenGigE0/1/0/0/0.1": {
        "ipv6_enabled": False,
        "int_status": "up",
        "oper_status": "down",
        "vrf": "vrf_601",
        "vrf_id": "0x6000025d",
        "enabled": False,
        "ipv6": {
            "2001:83:1:1::1/64": {
                "ipv6": "2001:83:1:1::1",
                "ipv6_prefix_length": "64",
                "ipv6_status": "tentative",
                "ipv6_subnet": "2001:83:1:1::",
            },
            "ipv6_link_local_state": "duplicate",
            "ipv6_link_local": "fe80::200:ff:fe00:1bcd",
            "ipv6_groups": [
                "ff02::1:ff00:1",
                "ff02::1:ff00:1bcd",
                "ff02::2",
                "ff02::1",
            ],
            "ipv6_mtu": "9108",
            "ipv6_mtu_available": "9090",
            "icmp_redirects": "disabled",
            "icmp_unreachables": "enabled",
            "nd_dad": "disabled",
            "dad_attempts": "0",
            "nd_reachable_time": "0",
            "nd_cache_limit": "0",
            "nd_adv_retrans_int": "0",
            "stateless_autoconfig": True,
            "table_id": "0xe080026c",
            "complete_protocol_adj": "0",
            "complete_glean_adj": "0",
            "incomplete_protocol_adj": "0",
            "incomplete_glean_adj": "0",
            "dropped_protocol_req": "0",
            "dropped_glean_req": "0",
        },
    },
}
