expected_output = {
    'tty': {
        '0': {
            'a': '-',
            'acci': '-',
            'acco': '-',
            'active': False,
            'int': '-',
            'line': 0,
            'modem': '-',
            'noise': 0,
            'overruns': '0/0',
            'roty': '-',
            'type': 'CTY',
            'uses': 0,
        },
        '1': {
            'a': '-',
            'acci': '-',
            'acco': '-',
            'active': False,
            'int': '-',
            'line': 1,
            'modem': '-',
            'noise': 0,
            'overruns': '0/0',
            'roty': '-',
            'rx': 9600,
            'tx': 9600,
            'type': 'AUX',
            'uses': 0,
        },
        '2': {
            'a': '-',
            'acci': '-',
            'acco': '-',
            'active': False,
            'int': '-',
            'line': 2,
            'modem': '-',
            'noise': 0,
            'overruns': '0/0',
            'roty': '-',
            'rx': 9600,
            'tx': 9600,
            'type': 'TTY',
            'uses': 0,
        },
        '0/0/0': {
            'a': '-',
            'acci': '-',
            'acco': '-',
            'active': False,
            'int': '-',
            'line': 3,
            'modem': '-',
            'noise': 513896,
            'overruns': '-1273299037/0',
            'roty': '-',
            'rx': 115200,
            'tx': 115200,
            'type': 'TTY',
            'uses': 557,
        },
        '0/0/3': {
            'a': '-',
            'acci': '-',
            'acco': '-',
            'active': False,
            'int': '-',
            'line': 6,
            'modem': '-',
            'noise': 1104886,
            'overruns': '-1524630269/0',
            'roty': '-',
            'rx': 115200,
            'tx': 115200,
            'type': 'TTY',
            'uses': 547,
        },
        '388': {
            'a': '-',
            'acci': '-',
            'acco': '-',
            'active': True,
            'int': '-',
            'line': 388,
            'modem': '-',
            'noise': 0,
            'overruns': '0/0',
            'roty': '-',
            'type': 'VTY',
            'uses': 820,
        },
    },
}
