expected_output = {
    'action': 'TRAP',
    'iif_id': '0000000000000090',
    'iif_name': 'GigabitEthernet3/0/28',
    'speed': '1000000000 BitsPerSecond',
    'traffic_type': {
        'BCAST': {
            'bytes': 0,
            'current_rate': 0,
            'level': 150000000,
            'low_level': 50000000,
            'packets': 0,
            'prev_bytes': 0,
            'prev_packets': 0,
            'storm_exists': 'No',
            'supp_type': 'BPS',
        },
        'MCAST': {
            'bytes': 0,
            'current_rate': 0,
            'level': 150000000,
            'low_level': 50000000,
            'packets': 0,
            'prev_bytes': 0,
            'prev_packets': 0,
            'storm_exists': 'No',
            'supp_type': 'BPS',
        },
        'SHARED': {
            'storm_control_not_configured': True,
        },
        'UCAST': {
            'bytes': 0,
            'current_rate': 0,
            'level': 150000000,
            'low_level': 50000000,
            'packets': 0,
            'prev_bytes': 0,
            'prev_packets': 0,
            'storm_exists': 'No',
            'supp_type': 'BPS',
        },
        'UNKNOWN_UCAST': {
            'bytes': 0,
            'current_rate': 0,
            'level': 150000000,
            'low_level': 50000000,
            'packets': 0,
            'prev_bytes': 0,
            'prev_packets': 0,
            'storm_exists': 'No',
            'supp_type': 'BPS',
        },
    },
}
