expected_output = {
    "autoconfig_status": "Enable",
    "vlans": {
        "Vlan1": {
            "state": "DONE",
            "l2": "Up",
            "created": "No",
            "initialized": "Yes",
            "ip_assign": (1, 0),
            "ip_state": (11, 0),
            "route": (1, 0),
            "static": (0, 0),
            "score": (8, 0),
            "allowed": (1, 1),
        },
        "Vlan100": {
            "state": "NONE",
            "l2": "Up",
            "created": "Yes",
            "initialized": "No",
            "ip_assign": (0, 0),
            "ip_state": (0, 0),
            "route": (0, 0),
            "static": (0, 0),
            "score": (0, 0),
            "allowed": (1, 1),
        },
        "Vlan110": {
            "state": "DONE",
            "l2": "Up",
            "created": "No",
            "initialized": "Yes",
            "ip_assign": (1, 1),
            "ip_state": (9, 9),
            "route": (0, 0),
            "static": (0, 0),
            "score": (4, 4),
            "allowed": (1, 1),
        },
        "Vlan120": {
            "state": "DONE",
            "l2": "Up",
            "created": "No",
            "initialized": "Yes",
            "ip_assign": (1, 1),
            "ip_state": (9, 9),
            "route": (0, 0),
            "static": (0, 0),
            "score": (4, 4),
            "allowed": (1, 1),
        },
        "Vlan130": {
            "state": "DONE",
            "l2": "Up",
            "created": "No",
            "initialized": "Yes",
            "ip_assign": (1, 1),
            "ip_state": (9, 9),
            "route": (0, 0),
            "static": (0, 0),
            "score": (4, 4),
            "allowed": (1, 1),
        },
    },
}
