expected_output = {
    "autoconfig_status": "Enable",
    "interfaces": {
        "Vlan1": {
            "uid": 1,
            "state": "DONE",
            "l2": "Up",
            "created": "No",
            "initialized": "Yes",
            "ip_assign": (1, 0),
            "ip_state": (11, 0),
            "route": (1, 0),
            "static": (0, 0),
            "score": (8, 0),
            "allowed": (1, 1),
        },
        "Vlan100": {
            "uid": 100,
            "state": "NONE",
            "l2": "Up",
            "created": "Yes",
            "initialized": "No",
            "ip_assign": (0, 0),
            "ip_state": (0, 0),
            "route": (0, 0),
            "static": (0, 0),
            "score": (0, 0),
            "allowed": (1, 1),
        },
        "Vlan110": {
            "uid": 110,
            "state": "DONE",
            "l2": "Up",
            "created": "No",
            "initialized": "Yes",
            "ip_assign": (1, 1),
            "ip_state": (9, 9),
            "route": (0, 0),
            "static": (0, 0),
            "score": (4, 4),
            "allowed": (1, 1),
        },
        "Vlan120": {
            "uid": 120,
            "state": "DONE",
            "l2": "Up",
            "created": "No",
            "initialized": "Yes",
            "ip_assign": (1, 1),
            "ip_state": (9, 9),
            "route": (0, 0),
            "static": (0, 0),
            "score": (4, 4),
            "allowed": (1, 1),
        },
        "Vlan130": {
            "uid": 130,
            "state": "DONE",
            "l2": "Up",
            "created": "No",
            "initialized": "Yes",
            "ip_assign": (1, 1),
            "ip_state": (9, 9),
            "route": (0, 0),
            "static": (0, 0),
            "score": (4, 4),
            "allowed": (1, 1),
        },
        "GigabitEthernet0/0": {
            "uid": 4101,
            "state": "DONE",
            "l2": "Up",
            "created": "No",
            "initialized": "Yes",
            "ip_assign": (1, 1),
            "ip_state": (7, 7),
            "route": (0, 0),
            "static": (1, 1),
            "score": (5, 0),
            "allowed": (1, 1),
        },
    },
}
