expected_output = {
    'sessions': {
        '90.0.0.10': {
            'interface': 'Gi0/0/5',
            'ld_rd': '4104/0',
            'rh_rs': 'Down',
            'state': 'Down',
        },
        '90.0.0.11': {
            'interface': 'Gi0/0/5',
            'ld_rd': '4105/0',
            'rh_rs': 'Down',
            'state': 'Down',
        },
        '90.0.0.12': {
            'interface': 'Gi0/0/5',
            'ld_rd': '4106/0',
            'rh_rs': 'Down',
            'state': 'Down',
        },
        '90.0.0.13': {
            'interface': 'Gi0/0/5',
            'ld_rd': '4107/0',
            'rh_rs': 'Down',
            'state': 'Down',
        },
        '90.0.0.14': {
            'interface': 'Gi0/0/5',
            'ld_rd': '4108/0',
            'rh_rs': 'Down',
            'state': 'Down',
        },
       '90.0.0.15': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4109/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.16': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4110/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.17': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4111/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.18': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4112/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.19': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4113/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.20': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4114/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.21': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4115/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.22': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4116/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.3': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4097/2',
           'rh_rs': 'Up',
           'state': 'Up',
       },
       '90.0.0.4': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4098/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.5': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4099/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.6': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4100/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.7': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4101/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.8': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4102/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
       '90.0.0.9': {
           'interface': 'Gi0/0/5',
           'ld_rd': '4103/0',
           'rh_rs': 'Down',
           'state': 'Down',
       },
   },
}
