expected_output = {
    'vrf': {
        'default': {
            'address_family': {
                'ipv4': {
                    'instance': {
                        100: {
                            'network': {
                                '10.100.0.1/32': {
                                    'advertising_router': '2.2.2.2',
                                    'checksum': '0xAED9',
                                    'external_route_tag': 65001,
                                    'length': 36,
                                    'link_state_id': '7',
                                    'ls_age': 22,
                                    'ls_seq_number': '80000001',
                                    'ls_type': 'AS External Link',
                                    'metric': 1,
                                    'metric_type': 2,
                                    'options': 'None',
                                    'prefix_address': '10.100.0.1',
                                    'prefix_length': 32,
                                },
                                '10.200.0.1/32': {
                                    'advertising_router': '2.2.2.2',
                                    'checksum': '0x8A73',
                                    'length': 32,
                                    'link_state_id': '5',
                                    'ls_age': 42,
                                    'ls_seq_number': '80000003',
                                    'ls_type': 'AS External Link',
                                    'metric': 20,
                                    'metric_type': 2,
                                    'options': 'None',
                                    'prefix_address': '10.200.0.1',
                                    'prefix_length': 32,
                                },
                                '10.30.0.1/32': {
                                    'advertising_router': '2.2.2.2',
                                    'checksum': '0xAC0B',
                                    'external_route_tag': 3300,
                                    'length': 36,
                                    'link_state_id': '0',
                                    'ls_age': 124,
                                    'ls_seq_number': '80000003',
                                    'ls_type': 'AS External Link',
                                    'metric': 20,
                                    'metric_type': 2,
                                    'options': 'None',
                                    'prefix_address': '10.30.0.1',
                                    'prefix_length': 32,
                                },
                                '10.50.0.0/24': {
                                    'advertising_router': '2.2.2.2',
                                    'checksum': '0x9FF8',
                                    'length': 32,
                                    'link_state_id': '1',
                                    'ls_age': 92,
                                    'ls_seq_number': '80000003',
                                    'ls_type': 'AS External Link',
                                    'metric': 33,
                                    'metric_type': 1,
                                    'options': 'None',
                                    'prefix_address': '10.50.0.0',
                                    'prefix_length': 24,
                                },
                            },
                            'router_id': '3.3.3.3',
                        },
                    },
                },
                'ipv6': {
                    'instance': {
                        100: {
                            'network': {
                                '2001:DB8:100::1/128': {
                                    'advertising_router': '2.2.2.2',
                                    'checksum': '0x7131',
                                    'external_route_tag': 65001,
                                    'length': 48,
                                    'link_state_id': '7',
                                    'ls_age': 22,
                                    'ls_seq_number': '80000001',
                                    'ls_type': 'AS External Link',
                                    'metric': 1,
                                    'metric_type': 2,
                                    'options': 'None',
                                    'prefix_address': '2001:DB8:100::1',
                                    'prefix_length': 128,
                                },
                                '2001:DB8:200::1/128': {
                                    'advertising_router': '2.2.2.2',
                                    'checksum': '0xC8B2',
                                    'length': 44,
                                    'link_state_id': '5',
                                    'ls_age': 42,
                                    'ls_seq_number': '80000003',
                                    'ls_type': 'AS External Link',
                                    'metric': 20,
                                    'metric_type': 2,
                                    'options': 'None',
                                    'prefix_address': '2001:DB8:200::1',
                                    'prefix_length': 128,
                                },
                                '2001:DB8:300::1/128': {
                                    'advertising_router': '2.2.2.2',
                                    'checksum': '0x3B4D',
                                    'external_route_tag': 3300,
                                    'length': 48,
                                    'link_state_id': '1',
                                    'ls_age': 125,
                                    'ls_seq_number': '80000003',
                                    'ls_type': 'AS External Link',
                                    'metric': 20,
                                    'metric_type': 2,
                                    'options': 'None',
                                    'prefix_address': '2001:DB8:300::1',
                                    'prefix_length': 128,
                                },
                                '2001:DB8:500::/64': {
                                    'advertising_router': '2.2.2.2',
                                    'checksum': '0x6A51',
                                    'length': 36,
                                    'link_state_id': '2',
                                    'ls_age': 92,
                                    'ls_seq_number': '80000003',
                                    'ls_type': 'AS External Link',
                                    'metric': 33,
                                    'metric_type': 1,
                                    'options': 'None',
                                    'prefix_address': '2001:DB8:500::',
                                    'prefix_length': 64,
                                },
                            },
                            'router_id': '3.3.3.3',
                        },
                    },
                },
            },
        },
    },
}
