expected_output = {'lisp_id': {0: {'site_name': {'site1': {'instance_id': {4: {'eid_prefix': {'all-named-services': {'last_registered': 'never',
                                                                                                   'up': 'no',
                                                                                                   'who_last_registered': '--'},
                                                                            'default-etr': {'last_registered': '00:05:52',
                                                                                            'port': 11323,
                                                                                            'up': 'yes',
                                                                                            'who_last_registered': '100.22.22.22'},
                                                                            'dual-stack': {'last_registered': '00:05:51',
                                                                                           'port': 63979,
                                                                                           'up': 'yes',
                                                                                           'who_last_registered': '100.11.11.11'},
                                                                            'firewall': {'last_registered': '00:05:51',
                                                                                         'port': 63979,
                                                                                         'up': 'yes',
                                                                                         'who_last_registered': '100.11.11.11'},
                                                                            'internet': {'last_registered': '00:05:52',
                                                                                         'port': 11323,
                                                                                         'up': 'yes',
                                                                                         'who_last_registered': '100.22.22.22'}}}}}}}}}
