expected_output={
    'main': {
        'chassis': {
            'C9550-24L4CD': {
                'descr': 'Cisco C9550-24L4CD Chassis',
                'name': 'Switch 2 Chassis',
                'pid': 'C9550-24L4CD',
                'sn': 'FDO294907P9',
                'vid': 'V00',
            },
        },
        'supervisor': {
            '1': {
                'descr': 'Cisco 9550-24L4CD Switch',
                'name': 'Switch 2 Slot 1 Supervisor',
                'pid': 'C9550-24L4CD',
                'sn': 'FDO294907P9',
                'vid': 'V00',
            },
        },
    },
    'slot': {
        '1': {
            'other': {
                'C9550-SSD-240G-V1': {
                    'descr': 'SSD disk',
                    'name': 'Switch 1  Disk0 SATA',
                    'pid': 'C9550-SSD-240G-V1',
                    'sn': 'MSA293707KS',
                    'vid': 'V00',
                },
                'C9K-PWR-750WAC': {
                    'descr': 'Cisco Switch 9550 Series 750W AC Power Supply',
                    'name': 'Switch 1 Power Supply Module 2',
                    'pid': 'C9K-PWR-750WAC',
                    'sn': 'MEG29450384',
                    'vid': 'V00',
                },
            },
            'pluggable': {
                'FiftyGigE1/0/1': {
                    'descr': '10GE CU1M',
                    'name': 'FiftyGigE1/0/1',
                    'pid': 'SFP-H10GB-CU1M',
                    'sn': 'TED2647A0YQ',
                    'vid': 'V03',
                },
                'FiftyGigE1/0/10': {
                    'descr': '10GE CU3M',
                    'name': 'FiftyGigE1/0/10',
                    'pid': 'SFP-H10GB-CU3M',
                    'sn': 'MPH2510A31S',
                    'vid': 'V03',
                },
                'FiftyGigE1/0/11': {
                    'descr': '10GE CU3M',
                    'name': 'FiftyGigE1/0/11',
                    'pid': 'SFP-H10GB-CU3M',
                    'sn': 'TED2310B8UT',
                    'vid': 'V03',
                },
                'FiftyGigE1/0/12': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE1/0/12',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21411019',
                    'vid': 'V01',
                },
                'FiftyGigE1/0/13': {
                    'descr': 'SFP 25GE AOC3M',
                    'name': 'FiftyGigE1/0/13',
                    'pid': 'SFP-25G-AOC3M',
                    'sn': 'FOF230300CL-B',
                    'vid': 'V01',
                },
                'FiftyGigE1/0/14': {
                    'descr': 'SFP 25GE AOC3M',
                    'name': 'FiftyGigE1/0/14',
                    'pid': 'SFP-25G-AOC3M',
                    'sn': 'FOF21410026-B',
                    'vid': 'V01',
                },
                'FiftyGigE1/0/15': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE1/0/15',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21411013',
                    'vid': 'V01',
                },
                'FiftyGigE1/0/16': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE1/0/16',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21411049',
                    'vid': 'V01',
                },
                'FiftyGigE1/0/17': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE1/0/17',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21410107',
                    'vid': 'V01',
                },
                'FiftyGigE1/0/18': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE1/0/18',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21410484',
                    'vid': 'V01',
                },
                'FiftyGigE1/0/19': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE1/0/19',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21401684',
                    'vid': 'V01',
                },
                'FiftyGigE1/0/2': {
                    'descr': '10GE CU1M',
                    'name': 'FiftyGigE1/0/2',
                    'pid': 'SFP-H10GB-CU1M',
                    'sn': 'TED2647A11X',
                    'vid': 'V03',
                },
                'FiftyGigE1/0/20': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE1/0/20',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21410082',
                    'vid': 'V01',
                },
                'FiftyGigE1/0/21': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE1/0/21',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21410466',
                    'vid': 'V01',
                },
                'FiftyGigE1/0/22': {
                    'descr': '10GE CU5M',
                    'name': 'FiftyGigE1/0/22',
                    'pid': 'SFP-H10GB-CU5M',
                    'sn': 'JPC2108019V',
                    'vid': 'V03',
                },
                'FiftyGigE1/0/23': {
                    'descr': 'GE T',
                    'name': 'FiftyGigE1/0/23',
                    'pid': 'GLC-TE',
                    'sn': 'AVC242904NF',
                    'vid': 'V03',
                },
                'FiftyGigE1/0/3': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE1/0/3',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21410468',
                    'vid': 'V01',
                },
                'FiftyGigE1/0/4': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE1/0/4',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21410514',
                    'vid': 'V01',
                },
                'FiftyGigE1/0/5': {
                    'descr': '10GE CU2M',
                    'name': 'FiftyGigE1/0/5',
                    'pid': 'SFP-H10GB-CU2M',
                    'sn': 'FCI24240185',
                    'vid': 'V02',
                },
                'FiftyGigE1/0/6': {
                    'descr': '10GE CU2M',
                    'name': 'FiftyGigE1/0/6',
                    'pid': 'SFP-H10GB-CU2M',
                    'sn': 'TED2315H2FF',
                    'vid': 'V02',
                },
                'FiftyGigE1/0/7': {
                    'descr': '10GE CU2M',
                    'name': 'FiftyGigE1/0/7',
                    'pid': 'SFP-H10GB-CU2M',
                    'sn': 'FCI242400Y5',
                    'vid': 'V02',
                },
                'FiftyGigE1/0/8': {
                    'descr': '10GE CU3M',
                    'name': 'FiftyGigE1/0/8',
                    'pid': 'SFP-H10GB-CU3M',
                    'sn': 'TED1925B5DJ',
                    'vid': 'V03',
                },
                'FiftyGigE1/0/9': {
                    'descr': '10GE CU3M',
                    'name': 'FiftyGigE1/0/9',
                    'pid': 'SFP-H10GB-CU3M',
                    'sn': 'TED1733B2LY',
                    'vid': 'V03',
                },
            },
            'rp': {
                'C9550-24L4CD': {
                    'descr': 'Cisco 9550-24L4CD Switch',
                    'name': 'Switch 2 Slot 1 Supervisor',
                    'pid': 'C9550-24L4CD',
                    'sn': 'FDO294907P9',
                    'vid': 'V00',
                },
            },
        },
        '2': {
            'other': {
                'C9550-SSD-240G-V1': {
                    'descr': 'SSD disk',
                    'name': 'Switch 2  Disk0 SATA',
                    'pid': 'C9550-SSD-240G-V1',
                    'sn': 'MSA293707KJ',
                    'vid': 'V00',
                },
                'C9K-PWR-750WAC': {
                    'descr': 'Cisco Switch 9550 Series 750W AC Power Supply',
                    'name': 'Switch 2 Power Supply Module 2',
                    'pid': 'C9K-PWR-750WAC',
                    'sn': 'MEG294503AD',
                    'vid': 'V00',
                },
            },
            'pluggable': {
                'FiftyGigE2/0/1': {
                    'descr': '10GE CU1M',
                    'name': 'FiftyGigE2/0/1',
                    'pid': 'SFP-H10GB-CU1M',
                    'sn': 'TED2647A0YQ',
                    'vid': 'V03',
                },
                'FiftyGigE2/0/10': {
                    'descr': '10GE CU3M',
                    'name': 'FiftyGigE2/0/10',
                    'pid': 'SFP-H10GB-CU3M',
                    'sn': 'MPH2510A31S',
                    'vid': 'V03',
                },
                'FiftyGigE2/0/11': {
                    'descr': '10GE CU3M',
                    'name': 'FiftyGigE2/0/11',
                    'pid': 'SFP-H10GB-CU3M',
                    'sn': 'TED2310B8UT',
                    'vid': 'V03',
                },
                'FiftyGigE2/0/12': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE2/0/12',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21411019',
                    'vid': 'V01',
                },
                'FiftyGigE2/0/13': {
                    'descr': 'SFP 25GE AOC3M',
                    'name': 'FiftyGigE2/0/13',
                    'pid': 'SFP-25G-AOC3M',
                    'sn': 'FOF230300CL-A',
                    'vid': 'V01',
                },
                'FiftyGigE2/0/14': {
                    'descr': 'SFP 25GE AOC3M',
                    'name': 'FiftyGigE2/0/14',
                    'pid': 'SFP-25G-AOC3M',
                    'sn': 'FOF21410026-A',
                    'vid': 'V01',
                },
                'FiftyGigE2/0/15': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE2/0/15',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21411013',
                    'vid': 'V01',
                },
                'FiftyGigE2/0/16': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE2/0/16',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21411049',
                    'vid': 'V01',
                },
                'FiftyGigE2/0/17': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE2/0/17',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21410107',
                    'vid': 'V01',
                },
                'FiftyGigE2/0/18': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE2/0/18',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21410484',
                    'vid': 'V01',
                },
                'FiftyGigE2/0/19': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE2/0/19',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21401684',
                    'vid': 'V01',
                },
                'FiftyGigE2/0/2': {
                    'descr': '10GE CU1M',
                    'name': 'FiftyGigE2/0/2',
                    'pid': 'SFP-H10GB-CU1M',
                    'sn': 'TED2647A11X',
                    'vid': 'V03',
                },
                'FiftyGigE2/0/20': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE2/0/20',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21410082',
                    'vid': 'V01',
                },
                'FiftyGigE2/0/21': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE2/0/21',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21410466',
                    'vid': 'V01',
                },
                'FiftyGigE2/0/22': {
                    'descr': '10GE CU5M',
                    'name': 'FiftyGigE2/0/22',
                    'pid': 'SFP-H10GB-CU5M',
                    'sn': 'JPC210801AE',
                    'vid': 'V03',
                },
                'FiftyGigE2/0/23': {
                    'descr': 'GE T',
                    'name': 'FiftyGigE2/0/23',
                    'pid': 'GLC-TE',
                    'sn': 'AVC242904M8',
                    'vid': 'V03',
                },
                'FiftyGigE2/0/24': {
                    'descr': '10GE CU5M',
                    'name': 'FiftyGigE2/0/24',
                    'pid': 'SFP-H10GB-CU5M',
                    'sn': 'JPC2108018P',
                    'vid': 'V03',
                },
                'FiftyGigE2/0/3': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE2/0/3',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21410468',
                    'vid': 'V01',
                },
                'FiftyGigE2/0/4': {
                    'descr': 'SFP 25GE CU3M',
                    'name': 'FiftyGigE2/0/4',
                    'pid': 'SFP-H25G-CU3M',
                    'sn': 'APF21410514',
                    'vid': 'V01',
                },
                'FiftyGigE2/0/5': {
                    'descr': '10GE CU2M',
                    'name': 'FiftyGigE2/0/5',
                    'pid': 'SFP-H10GB-CU2M',
                    'sn': 'FCI24240185',
                    'vid': 'V02',
                },
                'FiftyGigE2/0/6': {
                    'descr': '10GE CU2M',
                    'name': 'FiftyGigE2/0/6',
                    'pid': 'SFP-H10GB-CU2M',
                    'sn': 'TED2315H2FF',
                    'vid': 'V02',
                },
                'FiftyGigE2/0/7': {
                    'descr': '10GE CU2M',
                    'name': 'FiftyGigE2/0/7',
                    'pid': 'SFP-H10GB-CU2M',
                    'sn': 'FCI242400Y5',
                    'vid': 'V02',
                },
                'FiftyGigE2/0/8': {
                    'descr': '10GE CU3M',
                    'name': 'FiftyGigE2/0/8',
                    'pid': 'SFP-H10GB-CU3M',
                    'sn': 'TED1925B5DJ',
                    'vid': 'V03',
                },
                'FiftyGigE2/0/9': {
                    'descr': '10GE CU3M',
                    'name': 'FiftyGigE2/0/9',
                    'pid': 'SFP-H10GB-CU3M',
                    'sn': 'TED1733B2LY',
                    'vid': 'V03',
                },
            },
        },
        'Switch_1_Fan_Tray_1': {
            'other': {
                'C9550-FAN-1U-R': {
                    'descr': 'Cisco Switch 9550 Series 1RU Reverse Air Flow',
                    'name': 'Switch 1 Fan Tray 1',
                    'pid': 'C9550-FAN-1U-R',
                    'sn': 'DCH2946S71V',
                    'vid': 'V00',
                },
            },
        },
        'Switch_1_Fan_Tray_2': {
            'other': {
                'C9550-FAN-1U-R': {
                    'descr': 'Cisco Switch 9550 Series 1RU Reverse Air Flow',
                    'name': 'Switch 1 Fan Tray 2',
                    'pid': 'C9550-FAN-1U-R',
                    'sn': 'DCH2946S71U',
                    'vid': 'V00',
                },
            },
        },
        'Switch_1_Fan_Tray_3': {
            'other': {
                'C9550-FAN-1U-R': {
                    'descr': 'Cisco Switch 9550 Series 1RU Reverse Air Flow',
                    'name': 'Switch 1 Fan Tray 3',
                    'pid': 'C9550-FAN-1U-R',
                    'sn': 'DCH2946S72D',
                    'vid': 'V00',
                },
            },
        },
        'Switch_1_Fan_Tray_4': {
            'other': {
                'C9550-FAN-1U-R': {
                    'descr': 'Cisco Switch 9550 Series 1RU Reverse Air Flow',
                    'name': 'Switch 1 Fan Tray 4',
                    'pid': 'C9550-FAN-1U-R',
                    'sn': 'DCH2946S723',
                    'vid': 'V00',
                },
            },
        },
        'Switch_1_Fan_Tray_5': {
            'other': {
                'C9550-FAN-1U-R': {
                    'descr': 'Cisco Switch 9550 Series 1RU Reverse Air Flow',
                    'name': 'Switch 1 Fan Tray 5',
                    'pid': 'C9550-FAN-1U-R',
                    'sn': 'DCH2946S78Q',
                    'vid': 'V00',
                },
            },
        },
        'Switch_2_Fan_Tray_1': {
            'other': {
                'C9550-FAN-1U-R': {
                    'descr': 'Cisco Switch 9550 Series 1RU Reverse Air Flow',
                    'name': 'Switch 2 Fan Tray 1',
                    'pid': 'C9550-FAN-1U-R',
                    'sn': 'DCH2946S6VS',
                    'vid': 'V00',
                },
            },
        },
        'Switch_2_Fan_Tray_2': {
            'other': {
                'C9550-FAN-1U-R': {
                    'descr': 'Cisco Switch 9550 Series 1RU Reverse Air Flow',
                    'name': 'Switch 2 Fan Tray 2',
                    'pid': 'C9550-FAN-1U-R',
                    'sn': 'DCH2946S6UD',
                    'vid': 'V00',
                },
            },
        },
        'Switch_2_Fan_Tray_3': {
            'other': {
                'C9550-FAN-1U-R': {
                    'descr': 'Cisco Switch 9550 Series 1RU Reverse Air Flow',
                    'name': 'Switch 2 Fan Tray 3',
                    'pid': 'C9550-FAN-1U-R',
                    'sn': 'DCH2946S6ZG',
                    'vid': 'V00',
                },
            },
        },
        'Switch_2_Fan_Tray_4': {
            'other': {
                'C9550-FAN-1U-R': {
                    'descr': 'Cisco Switch 9550 Series 1RU Reverse Air Flow',
                    'name': 'Switch 2 Fan Tray 4',
                    'pid': 'C9550-FAN-1U-R',
                    'sn': 'DCH2946S6Z2',
                    'vid': 'V00',
                },
            },
        },
        'Switch_2_Fan_Tray_5': {
            'other': {
                'C9550-FAN-1U-R': {
                    'descr': 'Cisco Switch 9550 Series 1RU Reverse Air Flow',
                    'name': 'Switch 2 Fan Tray 5',
                    'pid': 'C9550-FAN-1U-R',
                    'sn': 'DCH2946S6UZ',
                    'vid': 'V00',
                },
            },
        },
    },
}