expected_output = {
    'chassis': {
        1: {
            'chassis_mac_address_lower_range': 'b08d.57ac.c340',
            'chassis_mac_address_upper_range': 'b08d.57ac.c37f',
            'number_of_mac_address': 64,
        },
        2: {
            'chassis_mac_address_lower_range': 'b08d.57ac.c300',
            'chassis_mac_address_upper_range': 'b08d.57ac.c33f',
            'number_of_mac_address': 64,
        },
    },
    'switches': {
        1: {
            'module': {
                1: {
                    'card_type': '30x40/100GE + 2x40/100/400GE',
                    'fw': '26.1.1r',
                    'hw': '1.0',
                    'mac_address': 'B08D.57C1.2180 to B08D.57C1.219F',
                    'model': 'C9600X-LC-32CD',
                    'ports': 32,
                    'serial': 'FDO281001KY',
                    'status': 'ok',
                    'sw': 'BLD_POLARIS_DEV_LA',
                },
                2: {
                    'card_type': 'Blank Module',
                    'model': 'C9610-BLANK',
                    'ports': 0,
                    'serial': 'N/A',
                },
                3: {
                    'card_type': 'Blank Module',
                    'model': 'C9610-BLANK',
                    'ports': 0,
                    'serial': 'N/A',
                },
                4: {
                    'card_type': 'Blank Module',
                    'model': 'C9610-BLANK',
                    'ports': 0,
                    'serial': 'N/A',
                },
                5: {
                    'card_type': 'Supervisor 3 Module',
                    'configured_redundancy_mode': 'sso',
                    'fw': '26.1.1r',
                    'hw': '0.9',
                    'mac_address': '8C44.A586.6E80 to 8C44.A586.6EFF',
                    'model': 'C9610-SUP-3',
                    'operating_redundancy_mode': 'sso',
                    'ports': 0,
                    'redundancy_role': 'active',
                    'serial': 'FDO28160V6Y',
                    'status': 'ok',
                    'sw': 'BLD_POLARIS_DEV_LA',
                },
                7: {
                    'card_type': '40x1/10/25/50GE + 2x200GE + 2x400GE',
                    'fw': '26.1.1r',
                    'hw': '1.0',
                    'mac_address': 'A0BC.6FCD.5A00 to A0BC.6FCD.5A7F',
                    'model': 'C9600-LC-40YL4CD',
                    'ports': 44,
                    'serial': 'FDO280906A6',
                    'status': 'ok',
                    'sw': 'BLD_POLARIS_DEV_LA',
                },
                8: {
                    'card_type': 'Blank Module',
                    'model': 'C9610-BLANK',
                    'ports': 0,
                    'serial': 'N/A',
                },
                9: {
                    'card_type': 'Blank Module',
                    'model': 'C9610-BLANK',
                    'ports': 0,
                    'serial': 'N/A',
                },
                10: {
                    'card_type': 'Blank Module',
                    'model': 'C9610-BLANK',
                    'ports': 0,
                    'serial': 'N/A',
                },
            },
        },
        2: {
            'module': {
                1: {
                    'card_type': '30x40/100GE + 2x40/100/400GE',
                    'fw': '17.18.1r',
                    'hw': '1.0',
                    'mac_address': 'B08D.57C0.C500 to B08D.57C0.C51F',
                    'model': 'C9600X-LC-32CD',
                    'ports': 32,
                    'serial': 'FDO2806000T',
                    'status': 'ok',
                    'sw': 'BLD_POLARIS_DEV_LA',
                },
                2: {
                    'card_type': 'Blank Module',
                    'model': 'C9610-BLANK',
                    'ports': 0,
                    'serial': 'N/A',
                },
                3: {
                    'card_type': 'Blank Module',
                    'model': 'C9610-BLANK',
                    'ports': 0,
                    'serial': 'N/A',
                },
                4: {
                    'card_type': 'Blank Module',
                    'model': 'C9610-BLANK',
                    'ports': 0,
                    'serial': 'N/A',
                },
                5: {
                    'card_type': 'Supervisor 3 Module',
                    'configured_redundancy_mode': 'sso',
                    'fw': '17.18.1r',
                    'hw': '0.9',
                    'mac_address': 'D47F.35A3.6A00 to D47F.35A3.6A7F',
                    'model': 'C9610-SUP-3',
                    'operating_redundancy_mode': 'sso',
                    'ports': 0,
                    'redundancy_role': 'standby',
                    'serial': 'FDO282714BH',
                    'status': 'ok',
                    'sw': 'BLD_POLARIS_DEV_LA',
                },
                7: {
                    'card_type': 'Blank Module',
                    'model': 'C9610-BLANK',
                    'ports': 0,
                    'serial': 'N/A',
                },
                8: {
                    'card_type': '40x1/10/25/50GE + 2x200GE + 2x400GE',
                    'fw': '17.18.1r',
                    'hw': '1.0',
                    'mac_address': 'A0BC.6FCD.5800 to A0BC.6FCD.587F',
                    'model': 'C9600-LC-40YL4CD',
                    'ports': 44,
                    'serial': 'FDO2809069N',
                    'status': 'ok',
                    'sw': 'BLD_POLARIS_DEV_LA',
                },
                9: {
                    'card_type': 'Blank Module',
                    'model': 'C9610-BLANK',
                    'ports': 0,
                    'serial': 'N/A',
                },
                10: {
                    'card_type': 'Blank Module',
                    'model': 'C9610-BLANK',
                    'ports': 0,
                    'serial': 'N/A',
                },
            },
        },
    },
}
