expected_output = {'lisp_id': {0: {'site_name': {'site1': {'instance_id': {4: {'eid_prefix': {'all-named-services': {'extranet_iid': 'Unspecified',
                                                                                                   'first_registered': 'never',
                                                                                                   'force_withdraw': 'No',
                                                                                                   'last_registered': 'never',
                                                                                                   'merge_active': 'No',
                                                                                                   'origin': 'Configuration, '
                                                                                                             'accepting '
                                                                                                             'more '
                                                                                                             'specifics',
                                                                                                   'proxy_reply': 'No',
                                                                                                   'registration_erros': {'allowed_locators_mismatch': 0,
                                                                                                                          'authentication_failures': 0},
                                                                                                   'routing_table_tag': 0,
                                                                                                   'skip_publication': 'Yes',
                                                                                                   'state': 'unknown',
                                                                                                   'ttl': '00:00:00'},
                                                                            'default-etr': {'etr': {'100.22.22.22': {'domain_id': '1',
                                                                                                                     'last_registered': '00:08:02',
                                                                                                                     'locators': {'100.22.22.22': {'local': 'yes',
                                                                                                                                                   'priority': 10,
                                                                                                                                                   'rdp': '[-]',
                                                                                                                                                   'scope': 'IPv4',
                                                                                                                                                   'state': 'up',
                                                                                                                                                   'weight': 50}},
                                                                                                                     'map_notify': True,
                                                                                                                     'multihoming_id': 'unspecified',
                                                                                                                     'nonce': '0xB0338BFE-0x13A33459',
                                                                                                                     'port': 11323,
                                                                                                                     'proxy_reply': True,
                                                                                                                     'state': 'complete',
                                                                                                                     'ttl': '1d00h',
                                                                                                                     'xtr_id': '0x610A78BA-0x7793BD60-0x9AFA7D91-0x3BC2F250'}},
                                                                                            'extranet_iid': 'Unspecified',
                                                                                            'first_registered': '00:08:07',
                                                                                            'force_withdraw': 'No',
                                                                                            'last_registered': '00:08:02',
                                                                                            'merge_active': 'No',
                                                                                            'origin': 'Dynamic, more '
                                                                                                      'specific of '
                                                                                                      'all-named-services',
                                                                                            'proxy_reply': 'Yes',
                                                                                            'registration_erros': {'allowed_locators_mismatch': 0,
                                                                                                                   'authentication_failures': 0},
                                                                                            'routing_table_tag': 0,
                                                                                            'skip_publication': 'No',
                                                                                            'state': 'complete',
                                                                                            'ttl': '1d00h'},
                                                                            'dual-stack': {'etr': {'100.11.11.11': {'domain_id': '1',
                                                                                                                    'last_registered': '00:08:01',
                                                                                                                    'locators': {'100.11.11.11': {'local': 'yes',
                                                                                                                                                  'priority': 10,
                                                                                                                                                  'rdp': '[-]',
                                                                                                                                                  'scope': 'IPv4',
                                                                                                                                                  'state': 'up',
                                                                                                                                                  'weight': 50}},
                                                                                                                    'map_notify': True,
                                                                                                                    'multihoming_id': 'unspecified',
                                                                                                                    'nonce': '0x0879AC24-0xB9E0AC4F',
                                                                                                                    'port': 63979,
                                                                                                                    'proxy_reply': True,
                                                                                                                    'state': 'complete',
                                                                                                                    'ttl': '1d00h',
                                                                                                                    'xtr_id': '0x448314C7-0xDE55C581-0xB1535180-0x5ABD34BD'}},
                                                                                           'extranet_iid': 'Unspecified',
                                                                                           'first_registered': '00:08:07',
                                                                                           'force_withdraw': 'No',
                                                                                           'last_registered': '00:08:01',
                                                                                           'merge_active': 'No',
                                                                                           'origin': 'Dynamic, more '
                                                                                                     'specific of '
                                                                                                     'all-named-services',
                                                                                           'proxy_reply': 'Yes',
                                                                                           'registration_erros': {'allowed_locators_mismatch': 0,
                                                                                                                  'authentication_failures': 0},
                                                                                           'routing_table_tag': 0,
                                                                                           'skip_publication': 'No',
                                                                                           'state': 'complete',
                                                                                           'ttl': '1d00h'},
                                                                            'firewall': {'etr': {'100.11.11.11': {'domain_id': '1',
                                                                                                                  'last_registered': '00:08:01',
                                                                                                                  'locators': {'100.11.11.11': {'local': 'yes',
                                                                                                                                                'priority': 10,
                                                                                                                                                'rdp': '[-]',
                                                                                                                                                'scope': 'IPv4',
                                                                                                                                                'state': 'up',
                                                                                                                                                'weight': 50}},
                                                                                                                  'map_notify': True,
                                                                                                                  'multihoming_id': 'unspecified',
                                                                                                                  'nonce': '0x0879AC24-0xB9E0AC4F',
                                                                                                                  'port': 63979,
                                                                                                                  'proxy_reply': True,
                                                                                                                  'state': 'complete',
                                                                                                                  'ttl': '1d00h',
                                                                                                                  'xtr_id': '0x448314C7-0xDE55C581-0xB1535180-0x5ABD34BD'}},
                                                                                         'extranet_iid': 'Unspecified',
                                                                                         'first_registered': '00:08:07',
                                                                                         'force_withdraw': 'No',
                                                                                         'last_registered': '00:08:01',
                                                                                         'merge_active': 'No',
                                                                                         'origin': 'Dynamic, more '
                                                                                                   'specific of '
                                                                                                   'all-named-services',
                                                                                         'proxy_reply': 'Yes',
                                                                                         'registration_erros': {'allowed_locators_mismatch': 0,
                                                                                                                'authentication_failures': 0},
                                                                                         'routing_table_tag': 0,
                                                                                         'skip_publication': 'No',
                                                                                         'state': 'complete',
                                                                                         'ttl': '1d00h'},
                                                                            'internet': {'etr': {'100.22.22.22': {'domain_id': '1',
                                                                                                                  'last_registered': '00:08:02',
                                                                                                                  'locators': {'100.22.22.22': {'local': 'yes',
                                                                                                                                                'priority': 10,
                                                                                                                                                'rdp': '[-]',
                                                                                                                                                'scope': 'IPv4',
                                                                                                                                                'state': 'up',
                                                                                                                                                'weight': 50}},
                                                                                                                  'map_notify': True,
                                                                                                                  'multihoming_id': 'unspecified',
                                                                                                                  'nonce': '0xB0338BFE-0x13A33459',
                                                                                                                  'port': 11323,
                                                                                                                  'proxy_reply': True,
                                                                                                                  'state': 'complete',
                                                                                                                  'ttl': '1d00h',
                                                                                                                  'xtr_id': '0x610A78BA-0x7793BD60-0x9AFA7D91-0x3BC2F250'}},
                                                                                         'extranet_iid': 'Unspecified',
                                                                                         'first_registered': '00:08:07',
                                                                                         'force_withdraw': 'No',
                                                                                         'last_registered': '00:08:02',
                                                                                         'merge_active': 'No',
                                                                                         'origin': 'Dynamic, more '
                                                                                                   'specific of '
                                                                                                   'all-named-services',
                                                                                         'proxy_reply': 'Yes',
                                                                                         'registration_erros': {'allowed_locators_mismatch': 0,
                                                                                                                'authentication_failures': 0},
                                                                                         'routing_table_tag': 0,
                                                                                         'skip_publication': 'No',
                                                                                         'state': 'complete',
                                                                                         'ttl': '1d00h'}}}}}}}}}
