expected_output = {'lisp_id': {0: {'site_name': {'site1': {'instance_id': {4: {'eid_prefix': {'dual-stack': {'etr': {'100.11.11.11': {'domain_id': '1',
                                                                                                                    'last_registered': '00:08:42',
                                                                                                                    'locators': {'100.11.11.11': {'local': 'yes',
                                                                                                                                                  'priority': 10,
                                                                                                                                                  'rdp': '[-]',
                                                                                                                                                  'scope': 'IPv4',
                                                                                                                                                  'state': 'up',
                                                                                                                                                  'weight': 50}},
                                                                                                                    'map_notify': True,
                                                                                                                    'multihoming_id': 'unspecified',
                                                                                                                    'nonce': '0x0879AC24-0xB9E0AC4F',
                                                                                                                    'port': 63979,
                                                                                                                    'proxy_reply': True,
                                                                                                                    'state': 'complete',
                                                                                                                    'ttl': '1d00h',
                                                                                                                    'xtr_id': '0x448314C7-0xDE55C581-0xB1535180-0x5ABD34BD'}},
                                                                                           'extranet_iid': 'Unspecified',
                                                                                           'first_registered': '00:08:47',
                                                                                           'force_withdraw': 'No',
                                                                                           'last_registered': '00:08:42',
                                                                                           'merge_active': 'No',
                                                                                           'origin': 'Dynamic, more '
                                                                                                     'specific of '
                                                                                                     'all-named-services',
                                                                                           'proxy_reply': 'Yes',
                                                                                           'registration_erros': {'allowed_locators_mismatch': 0,
                                                                                                                  'authentication_failures': 0},
                                                                                           'routing_table_tag': 0,
                                                                                           'skip_publication': 'No',
                                                                                           'state': 'complete',
                                                                                           'ttl': '1d00h'},
                                                                            'firewall': {'etr': {'100.11.11.11': {'domain_id': '1',
                                                                                                                  'last_registered': '00:08:42',
                                                                                                                  'locators': {'100.11.11.11': {'local': 'yes',
                                                                                                                                                'priority': 10,
                                                                                                                                                'rdp': '[-]',
                                                                                                                                                'scope': 'IPv4',
                                                                                                                                                'state': 'up',
                                                                                                                                                'weight': 50}},
                                                                                                                  'map_notify': True,
                                                                                                                  'multihoming_id': 'unspecified',
                                                                                                                  'nonce': '0x0879AC24-0xB9E0AC4F',
                                                                                                                  'port': 63979,
                                                                                                                  'proxy_reply': True,
                                                                                                                  'state': 'complete',
                                                                                                                  'ttl': '1d00h',
                                                                                                                  'xtr_id': '0x448314C7-0xDE55C581-0xB1535180-0x5ABD34BD'}},
                                                                                         'extranet_iid': 'Unspecified',
                                                                                         'first_registered': '00:08:47',
                                                                                         'force_withdraw': 'No',
                                                                                         'last_registered': '00:08:42',
                                                                                         'merge_active': 'No',
                                                                                         'origin': 'Dynamic, more '
                                                                                                   'specific of '
                                                                                                   'all-named-services',
                                                                                         'proxy_reply': 'Yes',
                                                                                         'registration_erros': {'allowed_locators_mismatch': 0,
                                                                                                                'authentication_failures': 0},
                                                                                         'routing_table_tag': 0,
                                                                                         'skip_publication': 'No',
                                                                                         'state': 'complete',
                                                                                         'ttl': '1d00h'}}}}}}}}}
