expected_output = {
    'vrf': {
        'default': {
            'address_family': {
                'ipv4': {
                    'instance': {
                        100: {
                            'router_id': '3.3.3.3',
                            'area': {
                                '10': {
                                    'network': {
                                        '0.0.0.0/0': {
                                            'ls_age': 8,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '10',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0xE043',
                                            'length': 28,
                                            'prefix_address': '0.0.0.0',
                                            'prefix_length': 0,
                                            'options': 'None',
                                            'metric_type': 2,
                                            'metric': 1,
                                        },
                                        '10.30.0.1/32': {
                                            'ls_age': 8,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '11',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0x8C4',
                                            'length': 36,
                                            'prefix_address': '10.30.0.1',
                                            'prefix_length': 32,
                                            'options': 'None',
                                            'metric_type': 2,
                                            'metric': 20,
                                            'external_route_tag': 3300,
                                        },
                                        '10.50.0.0/24': {
                                            'ls_age': 8,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '12',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0xFAB2',
                                            'length': 32,
                                            'prefix_address': '10.50.0.0',
                                            'prefix_length': 24,
                                            'options': 'None',
                                            'metric_type': 1,
                                            'metric': 33,
                                        },
                                        '10.100.0.1/32': {
                                            'ls_age': 8,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '13',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0x3868',
                                            'length': 36,
                                            'prefix_address': '10.100.0.1',
                                            'prefix_length': 32,
                                            'options': 'None',
                                            'metric_type': 2,
                                            'metric': 1,
                                            'external_route_tag': 65001,
                                        },
                                        '10.200.0.1/32': {
                                            'ls_age': 8,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '14',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0xF91B',
                                            'length': 32,
                                            'prefix_address': '10.200.0.1',
                                            'prefix_length': 32,
                                            'options': 'None',
                                            'metric_type': 2,
                                            'metric': 20,
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
                'ipv6': {
                    'instance': {
                        100: {
                            'router_id': '3.3.3.3',
                            'area': {
                                '10': {
                                    'network': {
                                        '::/0': {
                                            'ls_age': 8,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '10',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0x9E67',
                                            'length': 44,
                                            'prefix_address': '::',
                                            'prefix_length': 0,
                                            'options': 'None',
                                            'metric_type': 2,
                                            'metric': 1,
                                            'forward_address': '2001:DB8:23::2',
                                        },
                                        '2001:DB8:100::1/128': {
                                            'ls_age': 8,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '13',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0xFABF',
                                            'length': 48,
                                            'prefix_address': '2001:DB8:100::1',
                                            'prefix_length': 128,
                                            'options': 'None',
                                            'metric_type': 2,
                                            'metric': 1,
                                            'external_route_tag': 65001,
                                        },
                                        '2001:DB8:200::1/128': {
                                            'ls_age': 8,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '14',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0x385A',
                                            'length': 44,
                                            'prefix_address': '2001:DB8:200::1',
                                            'prefix_length': 128,
                                            'options': 'None',
                                            'metric_type': 2,
                                            'metric': 20,
                                        },
                                        '2001:DB8:300::1/128': {
                                            'ls_age': 8,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '15',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0x7822',
                                            'length': 48,
                                            'prefix_address': '2001:DB8:300::1',
                                            'prefix_length': 128,
                                            'options': 'None',
                                            'metric_type': 2,
                                            'metric': 20,
                                            'external_route_tag': 3300,
                                        },
                                        '2001:DB8:500::/64': {
                                            'ls_age': 8,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '16',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0xA726',
                                            'length': 36,
                                            'prefix_address': '2001:DB8:500::',
                                            'prefix_length': 64,
                                            'options': 'None',
                                            'metric_type': 1,
                                            'metric': 33,
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
    },
}
