expected_output = {
    'vrf': {
        'VRF1': {
            'address_family': {
                'ipv4': {
                    'instance': {
                        100: {
                            'router_id': '2.2.2.2',
                            'area': {
                                '10': {
                                    'network': {
                                        '10.40.0.1/32': {
                                            'ls_age': 62,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '0',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0x2986',
                                            'length': 36,
                                            'prefix_address': '10.40.0.1',
                                            'prefix_length': 32,
                                            'options': 'None',
                                            'metric_type': 2,
                                            'metric': 20,
                                            'external_route_tag': 3300,
                                        },
                                        '10.60.0.0/24': {
                                            'ls_age': 62,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '1',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0x1C74',
                                            'length': 32,
                                            'prefix_address': '10.60.0.0',
                                            'prefix_length': 24,
                                            'options': 'None',
                                            'metric_type': 1,
                                            'metric': 33,
                                        },
                                        '10.120.0.1/32': {
                                            'ls_age': 62,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '2',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0xE86A',
                                            'length': 32,
                                            'prefix_address': '10.120.0.1',
                                            'prefix_length': 32,
                                            'options': 'None',
                                            'metric_type': 2,
                                            'metric': 20,
                                        },
                                        '10.110.0.1/32': {
                                            'ls_age': 18,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '3',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0xCFA2',
                                            'length': 36,
                                            'prefix_address': '10.110.0.1',
                                            'prefix_length': 32,
                                            'options': 'DN',
                                            'metric_type': 2,
                                            'metric': 1,
                                            'external_route_tag': 65001,
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
                'ipv6': {
                    'instance': {
                        100: {
                            'router_id': '2.2.2.2',
                            'area': {
                                '10': {
                                    'network': {
                                        '2001:DB8:1200::1/128': {
                                            'ls_age': 62,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '0',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0xEF82',
                                            'length': 44,
                                            'prefix_address': (
                                                '2001:DB8:1200::1'
                                            ),
                                            'prefix_length': 128,
                                            'options': 'None',
                                            'metric_type': 2,
                                            'metric': 20,
                                        },
                                        '2001:DB8:400::1/128': {
                                            'ls_age': 62,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '1',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0x4E3B',
                                            'length': 48,
                                            'prefix_address': '2001:DB8:400::1',
                                            'prefix_length': 128,
                                            'options': 'None',
                                            'metric_type': 2,
                                            'metric': 20,
                                            'external_route_tag': 3300,
                                        },
                                        '2001:DB8:600::/64': {
                                            'ls_age': 62,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '2',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0x7D3F',
                                            'length': 36,
                                            'prefix_address': '2001:DB8:600::',
                                            'prefix_length': 64,
                                            'options': 'None',
                                            'metric_type': 1,
                                            'metric': 33,
                                        },
                                        '2001:DB8:1100::1/128': {
                                            'ls_age': 20,
                                            'ls_type': 'AS External Link',
                                            'link_state_id': '3',
                                            'advertising_router': '2.2.2.2',
                                            'ls_seq_number': '80000001',
                                            'checksum': '0xB7B',
                                            'length': 48,
                                            'prefix_address': (
                                                '2001:DB8:1100::1'
                                            ),
                                            'prefix_length': 128,
                                            'options': 'DN',
                                            'metric_type': 2,
                                            'metric': 1,
                                            'external_route_tag': 65001,
                                        },
                                    },
                                },
                            },
                        },
                    },
                },
            },
        },
    },
}
