expected_output = {
    'igmp_snooping_oper_state': 'Enabled',
    'igmpv3_snooping': 'Enabled',
    'report_supression': 'Enabled',
    'eht_db_limit': 100000,
    'eht_db_count': 0,
    'tcn_solicit_query': 'Disabled',
    'tcn_flood_query_count': 2,
    'robustness_variable': 2,
    'last_member_query_count': 2,
    'last_member_query_interval': 1000,
    'check_ttl': 'No',
    'check_router_alert_option': 'No',
    'vlan': {
        '1': {
            'igmp_snooping_admin_state': 'Enabled',
            'igmp_snooping_oper_state': 'Enabled',
            'igmpv2_immediate_leave': 'Disabled',
            'explicit_host_tracking': 'Enabled',
            'report_supression': 'Enabled',
            'eht_db_limit': 100000,
            'eht_db_count': 0,
            'robustness_variable': 2,
            'last_member_query_count': 2,
            'last_member_query_interval': 1000,
            'check_ttl': 'Yes',
            'check_router_alert_option': 'Yes',
        },
    },
}
