expected_output = {
    "interfaces":{
        "GigabitEthernet1/0/3":{
            "interface":"GigabitEthernet1/0/3",
            "role":"IP Phone 9971",
            "name":"SEP08CC68E9DB8A",
            "usage":"8.0",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "GigabitEthernet1/0/11":{
            "interface":"GigabitEthernet1/0/11",
            "role":"interface",
            "name":"Gi1.0.11",
            "usage":"10.7",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "GigabitEthernet1/0/14":{
            "interface":"GigabitEthernet1/0/14",
            "role":"IP Phone 9971",
            "name":"SEP34BDC8C7431D",
            "usage":"7.9",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "GigabitEthernet1/0/20":{
            "interface":"GigabitEthernet1/0/20",
            "role":"IP Phone 9971",
            "name":"SEP08CC6830C3B1",
            "usage":"6.5",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "GigabitEthernet1/0/21":{
            "interface":"GigabitEthernet1/0/21",
            "role":"IP Phone 9971",
            "name":"SEP28C7CED6CE44",
            "usage":"6.9",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "GigabitEthernet1/0/23":{
            "interface":"GigabitEthernet1/0/23",
            "role":"IP Phone 9951",
            "name":"SEPC40ACBE062FF",
            "usage":"7.4",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TwoGigabitEthernet2/0/15":{
            "interface":"TwoGigabitEthernet2/0/15",
            "role":"IP Phone 9971",
            "name":"SEPD4A02A8955FC",
            "usage":"7.6",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TwoGigabitEthernet2/0/24":{
            "interface":"TwoGigabitEthernet2/0/24",
            "role":"IP Phone 9971",
            "name":"SEP6886A7C43524",
            "usage":"7.6",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TwoGigabitEthernet2/0/32":{
            "interface":"TwoGigabitEthernet2/0/32",
            "role":"IP Phone 9971",
            "name":"SEP5C5015452E47",
            "usage":"6.6",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TenGigabitEthernet3/0/2":{
            "interface":"TenGigabitEthernet3/0/2",
            "role":"AIR-AP1261N-A-K9",
            "name":"ap",
            "usage":"6.3",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TenGigabitEthernet3/0/9":{
            "interface":"TenGigabitEthernet3/0/9",
            "role":"IP Phone 9861",
            "name":"SEP845A3EC21871",
            "usage":"4.0",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        },
        "TenGigabitEthernet3/0/10":{
            "interface":"TenGigabitEthernet3/0/10",
            "role":"IP Phone 9841",
            "name":"SEP0CD5D39EA585",
            "usage":"2.0",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"PoE"
        }
    },
    "device_models":{
        "76.0":{
            "usage":"76.0",
            "name":"Sust-PoE-3M-1",
            "role":"C9300-24P",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"parent"
        },
        "96.0":{
            "usage":"96.0",
            "name":"Sust-PoE-3M-2",
            "role":"C9300-48UXM",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"parent"
        },
        "118.0":{
            "usage":"118.0",
            "name":"Sust-PoE-3M-3",
            "role":"C9300X-24HX",
            "category":"consumer",
            "level":"10",
            "imp":"1",
            "type":"parent"
        },
        "consumer":371.5,
        "meter":0.0,
        "total":371.5,
        "count":15
    }
}
