expected_output = {
    'curr_flows': 5000,
    'index': {
        1: {
            'allow_bp': True,
            'app_name': 'dns',
            'bypass_pkt': 16,
            'clients': '0x01',
            'final': True,
            'flow_type': 'Real Flow',
            'ip1': '193.1.1.2',
            'ip2': '194.1.11.220',
            'l3_proto': 1,
            'l4_proto': 17,
            'pkts': 40,
            'port1': 53,
            'port2': 53,
            'swapped': 'No',
            'timeout_sec': 360,
            'tuple_type': 'Full',
            'vrf_vlan': 0,
        },
        10: {
            'allow_bp': True,
            'app_name': 'dns',
            'bypass_pkt': 16,
            'clients': '0x01',
            'final': True,
            'flow_type': 'Real Flow',
            'ip1': '193.1.1.2',
            'ip2': '194.1.6.80',
            'l3_proto': 1,
            'l4_proto': 17,
            'pkts': 40,
            'port1': 53,
            'port2': 53,
            'swapped': 'No',
            'timeout_sec': 360,
            'tuple_type': 'Full',
            'vrf_vlan': 0,
        },
        2: {
            'allow_bp': True,
            'app_name': 'dns',
            'bypass_pkt': 16,
            'clients': '0x01',
            'final': True,
            'flow_type': 'Real Flow',
            'ip1': '193.1.1.2',
            'ip2': '194.1.3.165',
            'l3_proto': 1,
            'l4_proto': 17,
            'pkts': 40,
            'port1': 53,
            'port2': 53,
            'swapped': 'No',
            'timeout_sec': 360,
            'tuple_type': 'Full',
            'vrf_vlan': 0,
        },
        3: {
            'allow_bp': True,
            'app_name': 'dns',
            'bypass_pkt': 16,
            'clients': '0x01',
            'final': True,
            'flow_type': 'Real Flow',
            'ip1': '193.1.1.2',
            'ip2': '194.1.13.106',
            'l3_proto': 1,
            'l4_proto': 17,
            'pkts': 40,
            'port1': 53,
            'port2': 53,
            'swapped': 'No',
            'timeout_sec': 360,
            'tuple_type': 'Full',
            'vrf_vlan': 0,
        },
        4: {
            'allow_bp': True,
            'app_name': 'dns',
            'bypass_pkt': 16,
            'clients': '0x01',
            'final': True,
            'flow_type': 'Real Flow',
            'ip1': '193.1.1.2',
            'ip2': '194.1.5.51',
            'l3_proto': 1,
            'l4_proto': 17,
            'pkts': 40,
            'port1': 53,
            'port2': 53,
            'swapped': 'No',
            'timeout_sec': 360,
            'tuple_type': 'Full',
            'vrf_vlan': 0,
        },
        5: {
            'allow_bp': True,
            'app_name': 'dns',
            'bypass_pkt': 16,
            'clients': '0x01',
            'final': True,
            'flow_type': 'Real Flow',
            'ip1': '193.1.1.2',
            'ip2': '194.1.18.20',
            'l3_proto': 1,
            'l4_proto': 17,
            'pkts': 40,
            'port1': 53,
            'port2': 53,
            'swapped': 'No',
            'timeout_sec': 360,
            'tuple_type': 'Full',
            'vrf_vlan': 0,
        },
        6: {
            'allow_bp': True,
            'app_name': 'dns',
            'bypass_pkt': 16,
            'clients': '0x01',
            'final': True,
            'flow_type': 'Real Flow',
            'ip1': '193.1.1.2',
            'ip2': '194.1.9.221',
            'l3_proto': 1,
            'l4_proto': 17,
            'pkts': 40,
            'port1': 53,
            'port2': 53,
            'swapped': 'No',
            'timeout_sec': 360,
            'tuple_type': 'Full',
            'vrf_vlan': 0,
        },
        7: {
            'allow_bp': True,
            'app_name': 'dns',
            'bypass_pkt': 16,
            'clients': '0x01',
            'final': True,
            'flow_type': 'Real Flow',
            'ip1': '193.1.1.2',
            'ip2': '194.1.1.166',
            'l3_proto': 1,
            'l4_proto': 17,
            'pkts': 40,
            'port1': 53,
            'port2': 53,
            'swapped': 'No',
            'timeout_sec': 360,
            'tuple_type': 'Full',
            'vrf_vlan': 0,
        },
        8: {
            'allow_bp': True,
            'app_name': 'dns',
            'bypass_pkt': 16,
            'clients': '0x01',
            'final': True,
            'flow_type': 'Real Flow',
            'ip1': '193.1.1.2',
            'ip2': '194.1.19.162',
            'l3_proto': 1,
            'l4_proto': 17,
            'pkts': 40,
            'port1': 53,
            'port2': 53,
            'swapped': 'No',
            'timeout_sec': 360,
            'tuple_type': 'Full',
            'vrf_vlan': 0,
        },
        9: {
            'allow_bp': True,
            'app_name': 'dns',
            'bypass_pkt': 16,
            'clients': '0x01',
            'final': True,
            'flow_type': 'Real Flow',
            'ip1': '193.1.1.2',
            'ip2': '194.1.11.107',
            'l3_proto': 1,
            'l4_proto': 17,
            'pkts': 40,
            'port1': 53,
            'port2': 53,
            'swapped': 'No',
            'timeout_sec': 360,
            'tuple_type': 'Full',
            'vrf_vlan': 0,
        },
    },
    'watermark': 5000,
}
