expected_output = {
    'curr_flows': 2,
    'index': {
        1: {
            'allow_bp': True,
            'app_name': 'facebook',
            'bypass_pkt': 3,
            'clients': '0x01',
            'final': True,
            'flow_type': 'Real Flow',
            'ip1': '20.0.0.2',
            'ip2': '30.0.0.2',
            'l3_proto': 1,
            'l4_proto': 6,
            'pkts': 40,
            'port1': 52059,
            'port2': 80,
            'swapped': 'Yes',
            'timeout_sec': 360,
            'tuple_type': 'Full',
            'vrf_vlan': 0,
        },
        2: {
            'allow_bp': True,
            'app_name': 'http',
            'bypass_pkt': 3,
            'clients': '0x01',
            'final': True,
            'flow_type': 'Real Flow',
            'ip1': '20.0.0.2',
            'ip2': '30.0.0.2',
            'l3_proto': 1,
            'l4_proto': 6,
            'pkts': 40,
            'port1': 80,
            'port2': 52059,
            'swapped': 'Yes',
            'timeout_sec': 360,
            'tuple_type': 'Full',
            'vrf_vlan': 0,
        },
    },
    'watermark': 3,
}
