expected_output =  {
    'flags': '0x0',
    'fvrf': 0,
    'if-id': '0x48b',
    'inbound_flow': {
        'auth_error_packets': 0,
        'control_packets': 0,
        'error_packets': 0,
        'flow_id': 53,
        'invalid_sa_packets': 0,
        'late_packets': 0,
        'sa_bytes': 5666,
        'sa_packets': 65,
        'spi': 1983646486,
        'vrf': '0',
    },
    'interface': 'Tunnel10',
    'ivrf': 4294967295,
    'outbound_flow': {
        'auth_error_packets': 0,
        'control_packets': 0,
        'error_packets': 0,
        'flow_id': 54,
        'invalid_sa_packets': 0,
        'late_packets': 0,
        'sa_bytes': 176405428,
        'sa_packets': 360062,
        'spi': 3559173000,
        'vrf': '0',
    },
    'sadb_id': '0xf',
    'sec_asic': 0,
    'sec_switch': 2,
}
