expected_output =  {
    'if-id': '0xec',
    'inbound_flow': {
        'anti_replay_fail': 0,
        'asic_instance': 'SA Stats',
        'auth_fail': 0,
        'byte_count': 10402760,
        'flow_id': 5,
        'invalid_sa': 0,
        'packet_count': 10020,
        'packet_format_check_error': 0,
        'sa_index': 1,
        'sequence_number_overflows': 0,
    },
    'outbound_flow': {
        'anti_replay_fail': 0,
        'asic_instance': 'SA Stats',
        'auth_fail': 0,
        'byte_count': 10663400,
        'flow_id': 6,
        'fvrf_id': 0,
        'invalid_sa': 0,
        'ivrf_id': 0,
        'packet_count': 10020,
        'packet_format_check_error': 0,
        'sa_index': 1026,
        'sequence_number_overflows': 0,
    },
}
