expected_output = {
    "cache_type": "Normal (Platform cache)",
    "cache_size": 200000,
    "current_entries": 3,
    "high_water_mark": 3,
    "flows_added": 3,
    "flows_aged": {"total": 0},
    "entries": {
        1: {
            "ipv4_dst_addr": "107.0.0.2",
            "tcp_flags": "0x00",
            "mpls_label_1_ttl": 255,
            "mpls_label_1_exp_bits": 6,
            "mpls_label_1_type": 0,
            "mpls_label_1": "6001   /6*",
            "ipv4_pw_dst_addr": "0.0.0.0",
            "ipv4_src_addr": "106.0.0.2",
            "intf_input": "Null",
            "intf_output": "GigabitEthernet0/0/8",
            "pkts": 7,
        },
        2: {
            "ipv4_dst_addr": "107.0.0.2",
            "tcp_flags": "0x10",
            "mpls_label_1_ttl": 255,
            "mpls_label_1_exp_bits": 6,
            "mpls_label_1_type": 0,
            "mpls_label_1": "6001   /6*",
            "ipv4_pw_dst_addr": "0.0.0.0",
            "ipv4_src_addr": "106.0.0.2",
            "intf_input": "Null",
            "intf_output": "GigabitEthernet0/0/8",
            "pkts": 2,
        },
        3: {
            "ipv4_dst_addr": "0.0.0.0",
            "tcp_flags": "0x00",
            "mpls_label_1_ttl": 255,
            "mpls_label_1_exp_bits": 0,
            "mpls_label_1_type": 0,
            "mpls_label_1": "6001   /0*",
            "ipv4_pw_dst_addr": "107.0.0.2",
            "ipv4_src_addr": "0.0.0.0",
            "intf_input": "Null",
            "intf_output": "GigabitEthernet0/0/8",
            "pkts": 14430784,
        },
    },
}
