expected_output = {
    "my_state": "13 -ACTIVE",
    "peer_state": "in progress to standby cold-bulk",
    "mode": "Duplex",
    "unit": "Primary",
    "unit_id": 1,
    "redundancy_mode_operational": "sso",
    "redundancy_mode_configured": "sso",
    "redundancy_state": "sso",
    "maintenance_mode": "Disabled",
    "manual_swact": "disabled",
    "manual_swact_reason": "peer unit not yet in terminal standby state",
    "communications": "Up",
    "client_count": 120,
    "client_notification_tmr_msec": 30000,
    "rf_debug_mask": "0x0",
    "current_client": "Igmp Snooping",
    "current_client_id": 506,
    "time_since_progression_msec": 91,
    "history_progression": "RF_PROG_STANDBY_BULK",
    "history_rc": 0,
}